services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-soignemoiproject}
      MYSQL_USER: ${DATABASE_USER:-soignemoi}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-soignemoipassword}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-soignemoipassword}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-soignemoipassword}

volumes:
  db_data:
