services:
  database:
    container_name: database.soignemoi
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-soignemoiproject}
      MYSQL_USER: ${DATABASE_USER:-soignemoi}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-soignemoipassword}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-soignemoipassword}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - database
    volumes:
      - ./volumes/soignemoi/database/data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin.soignemoi
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-soignemoipassword}
    networks:
      - database

networks:
  database: {}

volumes:
  database_data:
