api_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute